# Generated by Django 4.0.5 on 2022-07-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='calendar_month',
            field=models.CharField(choices=[('Ene', 'Enero'), ('Feb', 'Febrero'), ('Mar', 'Marzo'), ('Abr', 'Abril'), ('May', 'Mayo'), ('Jun', 'Junio'), ('Jul', 'Julio'), ('Ago', 'Agosto'), ('Sep', 'Septiembre'), ('Oct', 'Octubre'), ('Nov', 'Noviembre'), ('Dic', 'Diciembre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calendardayappointment',
            name='app_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='calendardayappointment',
            name='app_start_time',
            field=models.TimeField(),
        ),
    ]
